import { prisma } from "../db";
import { pairKey, persistValidPairsFromDb, readValidPairSetFromFile } from "./generateValidPairs";

export { pairKey, buildValidPairSet, persistValidPairsFromDb } from "./generateValidPairs";

let cached: Set<string> | null = null;
let building: Promise<Set<string>> | null = null;

/**
 * Valid team-pair set from `data/valid-pairs.json` only (committed artifact; regenerated by `db:load_data`).
 * The API does not scan `PlayerTeam` on cold start — run `npm run db:load_data` or `POST /boards/refresh-pairs` after DB changes.
 */
export async function getValidPairSet(): Promise<Set<string>> {
  if (cached) return cached;
  if (!building) {
    building = (async () => {
      const fromFile = readValidPairSetFromFile();
      if (!fromFile || fromFile.size === 0) {
        throw new Error(
          "Missing or empty backend/data/valid-pairs.json. Run `npm run db:load_data` in backend/ to regenerate.",
        );
      }
      return fromFile;
    })()
      .then((s) => {
        cached = s;
        building = null;
        return s;
      })
      .catch((e) => {
        building = null;
        throw e;
      });
  }
  return building;
}

export function invalidateValidPairCache(): void {
  cached = null;
}

/** Rebuild from DB, rewrite JSON, refresh memory cache. */
export async function refreshValidPairsFromDatabase(): Promise<Set<string>> {
  invalidateValidPairCache();
  const set = await persistValidPairsFromDb(prisma);
  cached = set;
  return set;
}

export function isBoardFullyValid(
  validPairs: Set<string>,
  triviaRow: string[],
  triviaColumn: string[],
  n: number,
): boolean {
  for (let row = 0; row < n; row += 1) {
    for (let col = 0; col < n; col += 1) {
      const top = triviaRow[col];
      const left = triviaColumn[row];
      if (!top || !left) return false;
      if (!validPairs.has(pairKey(top, left))) return false;
    }
  }
  return true;
}

function shuffleInPlace<T>(arr: T[]): void {
  for (let i = arr.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j]!, arr[i]!];
  }
}

const MAX_RANDOM_ATTEMPTS = 150;

/**
 * Random disjoint column headers (length `n`) and row headers (length `n`) from `pool` such that every
 * grid intersection has at least one player who played for both teams. Returns `null` if no layout found.
 */
export function sampleValidBoard(
  validPairs: Set<string>,
  pool: string[],
  n: number,
): { triviaRow: string[]; triviaColumn: string[] } | null {
  if (pool.length < 2 * n) return null;

  for (let attempt = 0; attempt < MAX_RANDOM_ATTEMPTS; attempt += 1) {
    const shuffled = [...pool];
    shuffleInPlace(shuffled);
    const picked = shuffled.slice(0, 2 * n);
    const triviaRow = picked.slice(0, n);
    const triviaColumn = picked.slice(n, 2 * n);
    if (isBoardFullyValid(validPairs, triviaRow, triviaColumn, n)) {
      return { triviaRow, triviaColumn };
    }
  }
  return null;
}
